using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace RelaxTimerApp
{
    public class LocalizationHelper : INotifyPropertyChanged
    {
        private static LocalizationHelper _instance;
        public static LocalizationHelper Instance => _instance ??= new LocalizationHelper();

        private string _currentLanguage = "en";
        public string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value;
                    OnPropertyChanged();
                    OnPropertyChanged("Item[]");
                }
            }
        }

        private Dictionary<string, Dictionary<string, string>> _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["en"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "RELAX TIMER",
                ["TimeForMyself"] = "TIME FOR MYSELF",
                ["Start"] = "START",
                ["Pause"] = "PAUSE",
                ["Reset"] = "RESET",
                ["Send"] = "SEND",
                ["Custom"] = "Custom",
                ["UserAgreementTitle"] = "User Agreement",
                ["Accept"] = "ACCEPT",
                ["Decline"] = "DECLINE",
                ["SelectLanguage"] = "SELECT LANGUAGE",
                ["AgreementText"] = "By using this application, you agree to take a moment for yourself, relax, and breathe. This tool is designed to assist with mental well-being but is not a substitute for professional help.\n\nDATA STORAGE: The only data stored by this application is your selected interface language preference, saved locally on your device.\n\nAI MODEL: This application uses GPT-2, a historical AI model, for educational purposes to familiarize users with the history and capabilities of early local AI models. GPT-2 represents an important milestone in the development of accessible, locally-run AI technology.",
                ["ChatPlaceholder"] = "Type your message here...",
                ["TimerFinished"] = "Timer Finished",
                ["Settings"] = "Settings",
                ["OpenLanguageSelection"] = "Language",
                ["OpenUserAgreement"] = "Agreement",
                ["ReportAIContent"] = "Report AI Content",
                ["CustomTimerTitle"] = "Custom Timer",
                ["SetTime"] = "Set Time:",
                ["InfiniteMode"] = "Infinity mode",
                ["FormatHint"] = "Format: HH:MM:SS",
                ["OK"] = "OK",
                ["Cancel"] = "Cancel",
                ["InvalidFormatMessage"] = "Enter correct time in format HH:MM:SS\nMax time: 10 hours",
                ["InvalidFormatTitle"] = "Invalid Format",
                ["User"] = "User",
                ["AI"] = "AI",
                ["Send"] = "✉️",
                ["Close"] = "CLOSE",
                ["ReportContentTitle"] = "Report AI Content",
                ["ReportContentDescription"] = "Please describe any inappropriate or concerning content generated by the AI. Your feedback helps improve the system.",
                ["SaveReport"] = "SAVE REPORT",
                ["ReportEmptyMessage"] = "Please enter a description of the issue before saving.",
                ["ReportEmptyTitle"] = "Empty Report",
                ["ReportSavedMessage"] = "Report has been saved successfully.",
                ["ReportSavedTitle"] = "Success",
                ["ReportSaveError"] = "Failed to save report:",
                ["Error"] = "Error",
                ["ReportAIContent"] = "Report AI"
            },
            ["uk"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "ТАЙМЕР РЕЛАКСАЦІЇ",
                ["TimeForMyself"] = "ЧАС ДЛЯ СЕБЕ",
                ["Start"] = "СТАРТ",
                ["Pause"] = "ПАУЗА",
                ["Reset"] = "СКИДАННЯ",
                ["Send"] = "НАДІСЛАТИ",
                ["Custom"] = "Власний",
                ["UserAgreementTitle"] = "Угода користувача",
                ["Accept"] = "ПРИЙНЯТИ",
                ["Decline"] = "ВІДХИЛИТИ",
                ["SelectLanguage"] = "ОБЕРІТЬ МОВУ",
                ["AgreementText"] = "Використовуючи цей додаток, ви погоджуєтесь приділити час собі, розслабитися і дихати. Цей інструмент створений для підтримки ментального благополуччя, але не замінює професійну допомогу.\n\nЗБЕРЕЖЕННЯ ДАНИХ: Єдині дані, що зберігаються цим додатком - це ваша поточна назва мови інтерфейсу, збережена локально на вашому пристрої.\n\nМОДЕЛЬ ШІ: Цей додаток використовує GPT-2, історичну модель ШІ, з освітньою метою для ознайомлення користувачів з історією та можливостями ранніх локальних моделей ШІ. GPT-2 представляє важливу віху в розвитку доступних локальних технологій штучного інтелекту.",
                ["ChatPlaceholder"] = "Введіть ваше повідомлення...",
                ["TimerFinished"] = "Таймер завершено",
                ["Settings"] = "Налаштування",
                ["OpenLanguageSelection"] = "Мова",
                ["OpenUserAgreement"] = "Угода",
                ["ReportAIContent"] = "Поскаржитися на контент AI",
                ["CustomTimerTitle"] = "Власний таймер",
                ["SetTime"] = "Встановіть час:",
                ["InfiniteMode"] = "Нескінченний режим",
                ["FormatHint"] = "Формат: ГГ:ХХ:СС",
                ["OK"] = "ОК",
                ["Cancel"] = "Скасувати",
                ["InvalidFormatMessage"] = "Введіть коректний час у форматі ГГ:ХХ:СС\nМаксимальний час: 10 годин",
                ["InvalidFormatTitle"] = "Неправильний формат",
                ["User"] = "Користувач",
                ["AI"] = "ШІ",
                ["Send"] = "✉️",
                ["Close"] = "ЗАКРИТИ",
                ["ReportContentTitle"] = "Поскаржитися на контент ШІ",
                ["ReportContentDescription"] = "Будь ласка, опишіть будь-який неприйнятний або проблемний контент, згенерований ШІ. Ваш відгук допомагає покращити систему.",
                ["SaveReport"] = "ЗБЕРЕГТИ СКАРГУ",
                ["ReportEmptyMessage"] = "Будь ласка, введіть опис проблеми перед збереженням.",
                ["ReportEmptyTitle"] = "Порожня скарга",
                ["ReportSavedMessage"] = "Скаргу успішно збережено.",
                ["ReportSavedTitle"] = "Успіх",
                ["ReportSaveError"] = "Не вдалося зберегти скаргу:",
                ["Error"] = "Помилка",
                ["ReportAIContent"] = "Скарга"
            },
            ["de"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "RELAX TIMER",
                ["TimeForMyself"] = "ZEIT FÜR MICH",
                ["Start"] = "START",
                ["Pause"] = "PAUSE",
                ["Reset"] = "ZURÜCKSETZEN",
                ["Send"] = "✉️",
                ["Custom"] = "Benutzerdefiniert",
                ["UserAgreementTitle"] = "Nutzungsvereinbarung",
                ["Accept"] = "AKZEPTIEREN",
                ["Decline"] = "ABLEHNEN",
                ["SelectLanguage"] = "SPRACHE WÄHLEN",
                ["AgreementText"] = "Mit der Nutzung dieser Anwendung verpflichten Sie sich, sich einen Moment Zeit für sich selbst zu nehmen, sich zu entspannen und zu atmen. Dieses Tool dient der Unterstützung des mentalen Wohlbefindens, ersetzt aber keine professionelle Hilfe.\n\nDATENSPEICHERUNG: Die einzigen von dieser Anwendung gespeicherten Daten sind Ihre ausgewählte Schnittstellensprache, die локально на Ihrem Gerät gespeichert wird.\n\nKI-MODELL: Diese Anwendung verwendet GPT-2, ein историческое KI-Modел, zu Bildungszwecken, um Benutzer mit der Geschichte und den Fähigkeiten früher локальних KI-Modelле vertraut zu machen. GPT-2 stellt einen wichtigen Meilenstein in der Entwicklung zugänglicher, lokal ausgeführter KI-Technologie dar.",
                ["ChatPlaceholder"] = "Geben Sie hier Ihre Nachricht ein...",
                ["TimerFinished"] = "Timer beendet",
                ["Settings"] = "Einstellungen",
                ["OpenLanguageSelection"] = "Sprache",
                ["OpenUserAgreement"] = "Vereinbarung",
                ["ReportAIContent"] = "KI-Inhalt melden",
                ["CustomTimerTitle"] = "Benutzerdefinierter Timer",
                ["SetTime"] = "Zeit einstellen:",
                ["InfiniteMode"] = "Unendlicher Modus",
                ["FormatHint"] = "Format: HH:MM:SS",
                ["OK"] = "OK",
                ["Cancel"] = "Abbrechen",
                ["InvalidFormatMessage"] = "Geben Sie die korrekte Zeit im Format HH:MM:SS ein\nMaximale Zeit: 10 Stunden",
                ["InvalidFormatTitle"] = "Ungültiges Format",
                ["User"] = "Benutzer",
                ["AI"] = "KI",
                ["Close"] = "SCHLIEẞEN",
                ["ReportContentTitle"] = "KI-Inhalt melden",
                ["ReportContentDescription"] = "Bitte beschreiben Sie unangemessene oder bedenkliche von der KI generierte Inhalte. Ihr Feedback hilft, das System zu verbessern.",
                ["SaveReport"] = "BERICHT SPEICHERN",
                ["ReportEmptyMessage"] = "Bitte geben Sie eine Beschreibung des Problems ein, bevor Sie speichern.",
                ["ReportEmptyTitle"] = "Leerer Bericht",
                ["ReportSavedMessage"] = "Bericht wurde erfolgreich gespeichert.",
                ["ReportSavedTitle"] = "Erfolg",
                ["ReportSaveError"] = "Fehler beim Speichern des Berichts:",
                ["Error"] = "Fehler",
                ["ReportAIContent"] = "KI melden"
            },
            ["tr"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "RELAX TIMER",
                ["TimeForMyself"] = "KENDİME ZAMAN",
                ["Start"] = "BAŞLAT",
                ["Pause"] = "DURAKLAT",
                ["Reset"] = "SIFIRLA",
                ["Send"] = "✉️",
                ["Custom"] = "Özel",
                ["UserAgreementTitle"] = "Kullanıcı Sözleşmesi",
                ["Accept"] = "KABUL ET",
                ["Decline"] = "REDDET",
                ["SelectLanguage"] = "DİL SEÇİN",
                ["AgreementText"] = "Bu uygulamayı kullanarak, kendinize bir an ayırmayı, rahatlamayı ve nefes almayı kabul ediyorsunuz. Bu araç zihinsel sağlığa yardımcı olmak için tasarlanmıştır ancak profesyonel yardımın yerine geçmez.\n\nVERİ DEPOLAMA: Bu uygulama tarafından depolanan tek veri, cihazınızda yerel olarak kaydedilen seçili arayüz dili tercihinizdir.\n\nYZ MODELİ: Bu uygulama, kullanıcıları erken dönem yerel YZ modellerinin tarihi ve yetenekleri ile tanıştırmak için eğitim amaçlı tarihi bir YZ modeli olan GPT-2 kullanır. GPT-2, erişilebilir, yerel olarak çalışan YZ teknolojisinin gelişiminde önemli bir kilometre taşını temsil eder.",
                ["ChatPlaceholder"] = "Mesajınızı buraya yazın...",
                ["TimerFinished"] = "Zamanlayıcı Bitti",
                ["Settings"] = "Ayarlar",
                ["OpenLanguageSelection"] = "Dil",
                ["OpenUserAgreement"] = "Sözleşme",
                ["CustomTimerTitle"] = "Özel Zamanlayıcı",
                ["SetTime"] = "Zamanı Ayarla:",
                ["InfiniteMode"] = "Sonsuz mod",
                ["FormatHint"] = "Format: SS:DD:SS",
                ["OK"] = "TAMAM",
                ["Cancel"] = "İptal",
                ["InvalidFormatMessage"] = "Doğru zamanı SS:DD:SS formatında girin\nMaksimum süre: 10 saat",
                ["InvalidFormatTitle"] = "Geçersiz Format",
                ["User"] = "Kullanıcı",
                ["AI"] = "YZ",
                ["Close"] = "KAPAT",
                ["ReportContentTitle"] = "YZ İçeriğini Bildir",
                ["ReportContentDescription"] = "Lütfen YZ tarafından oluşturulan uygunsuz veya endişe verici içeriği açıklayın. Geri bildiriminiz sistemin iyileştirilmesine yardımcı olur.",
                ["SaveReport"] = "RAPORU KAYDET",
                ["ReportEmptyMessage"] = "Lütfen kaydetmeden önce sorunun açıklamasını girin.",
                ["ReportEmptyTitle"] = "Boş Rapor",
                ["ReportSavedMessage"] = "Rapor başarıyla kaydedildi.",
                ["ReportSavedTitle"] = "Başarılı",
                ["ReportSaveError"] = "Rapor kaydedilirken hata:",
                ["Error"] = "Hata",
                ["ReportAIContent"] = "YZ Bildir"
            },
            ["ru"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "RELAX TIMER",
                ["TimeForMyself"] = "ВРЕМЯ ДЛЯ СЕБЯ",
                ["Start"] = "СТАРТ",
                ["Pause"] = "ПАУЗА",
                ["Reset"] = "СБРОС",
                ["Send"] = "✉️",
                ["Custom"] = "Пользовательский",
                ["UserAgreementTitle"] = "Пользовательское соглашение",
                ["Accept"] = "ПРИНЯТЬ",
                ["Decline"] = "ОТКЛОНИТЬ",
                ["SelectLanguage"] = "ВЫБЕРИТЕ ЯЗЫК",
                ["AgreementText"] = "Используя это приложение, вы соглашаетесь уделить время себе, расслабиться и дышать. Этот инструмент предназначен для поддержки психического благополучия, но не заменяет профессиональную помощь.\n\nХРАНЕНИЕ ДАННЫХ: Единственные данные, хранимые этим приложением - это выбранный вами язык интерфейса, сохраненный локально на вашем устройстве.\n\nМОДЕЛЬ ИИ: Это приложение использует GPT-2, историческую модель ИИ, в образовательных целях для ознакомления пользователей с историей и возможностями ранних локальных моделей ИИ. GPT-2 представляет важную веху в развитии доступных локально работающих технологий искусственного интеллекта.",
                ["ChatPlaceholder"] = "Введите ваше сообщение здесь...",
                ["TimerFinished"] = "Таймер завершён",
                ["Settings"] = "Настройки",
                ["OpenLanguageSelection"] = "Язык",
                ["OpenUserAgreement"] = "Соглашение",
                ["CustomTimerTitle"] = "Пользовательский таймер",
                ["SetTime"] = "Установить время:",
                ["InfiniteMode"] = "Бесконечный режим",
                ["FormatHint"] = "Формат: ЧЧ:ММ:СС",
                ["OK"] = "OK",
                ["Cancel"] = "Отмена",
                ["InvalidFormatMessage"] = "Введите правильное время в формате ЧЧ:ММ:СС\nМаксимальное время: 10 часов",
                ["InvalidFormatTitle"] = "Неверный формат",
                ["User"] = "Пользователь",
                ["AI"] = "ИИ",
                ["Close"] = "ЗАКРЫТЬ",
                ["ReportContentTitle"] = "Пожаловаться на контент ИИ",
                ["ReportContentDescription"] = "Пожалуйста, опишите любой неприемлемый или вызывающий беспокойство контент, созданный ИИ. Ваш отзыв помогает улучшить систему.",
                ["SaveReport"] = "СОХРАНИТЬ ЖАЛОБУ",
                ["ReportEmptyMessage"] = "Пожалуйста, введите описание проблемы перед сохранением.",
                ["ReportEmptyTitle"] = "Пустая жалоба",
                ["ReportSavedMessage"] = "Жалоба успешно сохранена.",
                ["ReportSavedTitle"] = "Успех",
                ["ReportSaveError"] = "Не удалось сохранить жалобу:",
                ["Error"] = "Ошибка",
                ["ReportAIContent"] = "Жалоба"
            }
        };

        public string this[string key]
        {
            get
            {
                if (_translations.ContainsKey(_currentLanguage) && _translations[_currentLanguage].ContainsKey(key))
                {
                    return _translations[_currentLanguage][key];
                }
                // Fallback to English if key missing in current language
                if (_translations["en"].ContainsKey(key))
                {
                    return _translations["en"][key];
                }
                return key;
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
